#!/bin/bash
# Quick check script voor Vercel environment variables

echo "🔍 Checking Vercel Environment Variables..."
echo ""
echo "Ga naar: https://vercel.com/ayoubelkaoui/akws-new/settings/environment-variables"
echo ""
echo "✅ Controleer dat deze 3 variables bestaan voor Production:"
echo ""
echo "1. PUBLIC_RECAPTCHA_SITE_KEY"
echo "   Waarde: 6Lfg5fErAAAAAFNB6fEZq1TBrAKH1zysHKXVhCZv"
echo ""
echo "2. RECAPTCHA_SECRET_KEY"
echo "   Waarde: 6Lfg5fErAAAAABsG4FVv3gI557TCpI2CdZuW08HO"
echo ""
echo "3. RESEND_API_KEY"
echo "   Waarde: re_... (haal deze op van https://resend.com/api-keys)"
echo ""
echo "⚠️  BELANGRIJK:"
echo "   - Resend API key moet beginnen met 're_'"
echo "   - Moet 'Full access' of 'Sending access' permissions hebben"
echo "   - Als je geen key hebt, maak er een aan in Resend dashboard"
echo ""
echo "📝 Stappen:"
echo "   1. Open Vercel Settings → Environment Variables"
echo "   2. Voeg RESEND_API_KEY toe als die ontbreekt"
echo "   3. Klik 'Save'"
echo "   4. Ga naar Deployments → klik '...' → 'Redeploy'"
echo "   5. Wacht 1-2 minuten"
echo "   6. Test op: https://akwebsolutions.nl/contact"
echo ""
